

= 30.08.2022 16:21:42 (UTC +8:00) === ECU-TEST 2022.2.125314+1e79c4002501 125314+1e79c4002501 (2022/06/14 12:33:44) (64bit) ===
Python 3.9.7 (tags/v3.9.7:1016ef3, Aug 30 2021, 20:19:38) [MSC v.1929 64 bit (AMD64)]

Roaming License: ECU-TEST
         - License options:
             + Diagnostics add-on
             + Trace Analysis
         - valid up to version: 2022.4
         - valid until: 14-sep-2022
         - licensed for: TURING


2022-08-30 16:21:42.956 9260 ManagedWorker-2*PE.Run() ERROR:
                        Traceback (most recent call last):
                          File "tts\core\toolingFramework\toolAccess\LockProxy.py", line 55, in __call__
                          File "tts\core\toolingFramework\interface\portTypes\AbstractBusAccessPort.py", line 491, in InitNode
                        NotImplementedError: InitNode
                        
                        The above exception was the direct cause of the following exception:
                        
                        Traceback (most recent call last):
                          File "tts\core\package\engine\ExecutionMappingSpaceManager.py", line 631, in __CallRegisterXaObjects
                          File "tts\testModule\bus\mapping\XABusNodeVariableExec.py", line 13, in PrepareRead
                          File "tts\core\toolingFramework\toolAccess\LockProxy.py", line 68, in __call__
                          File "tts\core\toolingFramework\toolAccess\LockProxy.py", line 94, in ReportToolError
                        tts.core.toolingFramework.toolAccess.Exceptions.ToolError: Port BUS-CAN_MANIP01 (@local): PortInitNode() failed: InitNode
